import { commonProcessor } from './components/common/CommonProcessor';
import { pageContentProcessor } from './components/content-types/page/PageContentProcessor';
import { fourColumnProcessor } from './components/layouts/fourcolumn/FourColumnProcessor';
import { fourColumn2RowProcessor } from './components/layouts/fourcolumn2row/FourColumn2RowProcessor';
import { singleColumnProcessor } from './components/layouts/singlecolumn/SingleColumnProcessor';
import { singleColumn2RowProcessor } from './components/layouts/singlecolumn2row/SingleColumn2RowProcessor';
import { threeColumnProcessor } from './components/layouts/threecolumn/ThreeColumnProcessor';
import { threeColumn2RowProcessor } from './components/layouts/threecolumn2row/ThreeColumn2RowProcessor';
import { twoColumnProcessor } from './components/layouts/twocolumn/TwoColumnProcessor';
import { twoColumn2RowProcessor } from './components/layouts/twocolumn2row/TwoColumn2RowProcessor';
import { underConstructionProcessor } from './components/layouts/under-construction/UnderConstructionProcessor';
import { pageProcessor } from './components/pages/Page/PageProcessor';
import { underConstructionPageProcessor } from './components/pages/under-construction/UnderConstructionPageProcessor';
import { articleProcessor } from './components/parts/article/ArticleProcessor';
import { articleListProcessor } from './components/parts/articlelist/ArticleListProcessor';
import { boardProcessor } from './components/parts/board/BoardProcessor';
import { boardPresentationProcessor } from './components/parts/boardpresentation/BoardPresentationProcessor';
import { bookProcessor } from './components/parts/book/BookProcessor';
import { bookListProcessor } from './components/parts/booklist/BookListProcessor';
import { budgetCutListProcessor } from './components/parts/budgetcutlist/BudgetCutListProcessor';
import { buttonProcessor } from './components/parts/button/ButtonProcessor';
import { candidateBlockProcessor } from './components/parts/candidateblock/CandidateBlockProcessor';
import { candidateListProcessor } from './components/parts/candidatelist/CandidateListProcessor';
import { candidatePageProcessor } from './components/parts/candidatepage/CandidatePageProcessor';
import { candidatePresentationProcessor } from './components/parts/candidatepresentation/CandidatePresentationProcessor';
import { eventProcessor } from './components/parts/event/EventProcessor';
import { eventListProcessor } from './components/parts/eventlist/EventListProcessor';
import { fancyHeaderProcessor } from './components/parts/fancyheader/FancyHeaderProcessor';
import { faqProcessor } from './components/parts/faq/FaqProcessor';
import { faqListProcessor } from './components/parts/faqlist/FaqListProcessor';
import { groupProcessor } from './components/parts/group/GroupProcessor';
import { imageBlockProcessor } from './components/parts/imageblock/ImageBlockProcessor';
import { introBlockProcessor } from './components/parts/introblock/IntroBlockProcessor';
import { joinProcessor } from './components/parts/join/JoinProcessor';
import { localBlockProcessor } from './components/parts/localblock/LocalBlockProcessor';
import { localBranchProcessor } from './components/parts/localbranch/LocalBranchProcessor';
import { localBranchesProcessor } from './components/parts/localbranches/LocalBranchesProcessor';
import { missionsBlockProcessor } from './components/parts/missionsblock/MissionsBlockProcessor';
import { organizationalPositionProcessor } from './components/parts/organizational-position/OrganizationalPositionProcessor';
import { pageListProcessor } from './components/parts/pagelist/PageListProcessor';
import { personProcessor } from './components/parts/person/PersonProcessor';
import { personListProcessor } from './components/parts/personlist/PersonListProcessor';
import { programmeMainProcessor } from './components/parts/programme-main/ProgrammeMainProcessor';
import { programmePartProcessor } from './components/parts/programme-part/ProgrammePartProcessor';
import { programmeSectionProcessor } from './components/parts/programme-section/ProgrammeSectionProcessor';
import { quoteProcessor } from './components/parts/quote/QuoteProcessor';
import { submenuProcessor } from './components/parts/submenu/SubmenuProcessor';
import { testProcessor } from './components/parts/test/TestProcessor';
import { textBlockProcessor } from './components/parts/textblock/TextBlockProcessor';
import { titleBlockProcessor } from './components/parts/titleblock/TitleBlockProcessor';
import { DataFetcher } from '/lib/enonic/react4xp';

export const dataFetcher = new DataFetcher();

// portal:site must be registered for Content Studio Live Edit to work
// When a page descriptor is selected, app.ts will use the page processor instead
dataFetcher.addCommon({ processor: commonProcessor });

dataFetcher.addContentType('portal:site', {processor: pageContentProcessor});

dataFetcher.addLayout('lib.no:singlecolumn', {processor: singleColumnProcessor});
dataFetcher.addLayout('lib.no:twocolumn', {processor: twoColumnProcessor});
dataFetcher.addLayout('lib.no:threecolumn', {processor: threeColumnProcessor});
dataFetcher.addLayout('lib.no:fourcolumn', {processor: fourColumnProcessor});
dataFetcher.addLayout('lib.no:singlecolumn2row', {processor: singleColumn2RowProcessor});
dataFetcher.addLayout('lib.no:twocolumn2row', {processor: twoColumn2RowProcessor});
dataFetcher.addLayout('lib.no:threecolumn2row', {processor: threeColumn2RowProcessor});
dataFetcher.addLayout('lib.no:fourcolumn2row', {processor: fourColumn2RowProcessor});
dataFetcher.addLayout('lib.no:under-construction', {processor: underConstructionProcessor});

dataFetcher.addPage('lib.no:default', {processor: pageProcessor});
dataFetcher.addPage('lib.no:under-construction', {processor: underConstructionPageProcessor});

dataFetcher.addPart('lib.no:article', {processor: articleProcessor});
dataFetcher.addPart('lib.no:articlelist', {processor: articleListProcessor});
dataFetcher.addPart('lib.no:board', {processor: boardProcessor});
dataFetcher.addPart('lib.no:boardpresentation', {processor: boardPresentationProcessor});
dataFetcher.addPart('lib.no:book', {processor: bookProcessor});
dataFetcher.addPart('lib.no:booklist', {processor: bookListProcessor});
dataFetcher.addPart('lib.no:budgetcutlist', {processor: budgetCutListProcessor});
dataFetcher.addPart('lib.no:button', {processor: buttonProcessor});
dataFetcher.addPart('lib.no:candidateblock', {processor: candidateBlockProcessor});
dataFetcher.addPart('lib.no:candidatelist', {processor: candidateListProcessor});
dataFetcher.addPart('lib.no:candidatepage', {processor: candidatePageProcessor});
dataFetcher.addPart('lib.no:candidatepresentation', {processor: candidatePresentationProcessor});
dataFetcher.addPart('lib.no:event', {processor: eventProcessor});
dataFetcher.addPart('lib.no:eventlist', {processor: eventListProcessor});
dataFetcher.addPart('lib.no:fancyheader', {processor: fancyHeaderProcessor});
dataFetcher.addPart('lib.no:faq', {processor: faqProcessor});
dataFetcher.addPart('lib.no:faqlist', {processor: faqListProcessor});
dataFetcher.addPart('lib.no:group', {processor: groupProcessor});
dataFetcher.addPart('lib.no:imageblock', {processor: imageBlockProcessor});
dataFetcher.addPart('lib.no:introblock', {processor: introBlockProcessor});
dataFetcher.addPart('lib.no:join', {processor: joinProcessor});
dataFetcher.addPart('lib.no:localblock', {processor: localBlockProcessor});
dataFetcher.addPart('lib.no:localbranch', {processor: localBranchProcessor});
dataFetcher.addPart('lib.no:localbranches', {processor: localBranchesProcessor});
dataFetcher.addPart('lib.no:missionsblock', {processor: missionsBlockProcessor});
dataFetcher.addPart('lib.no:organizational-position', {processor: organizationalPositionProcessor});
dataFetcher.addPart('lib.no:pagelist', {processor: pageListProcessor});
dataFetcher.addPart('lib.no:person', {processor: personProcessor});
dataFetcher.addPart('lib.no:personlist', {processor: personListProcessor});
dataFetcher.addPart('lib.no:programme-main', {processor: programmeMainProcessor});
dataFetcher.addPart('lib.no:programme-part', {processor: programmePartProcessor});
dataFetcher.addPart('lib.no:programme-section', {processor: programmeSectionProcessor});
dataFetcher.addPart('lib.no:quote', {processor: quoteProcessor});
dataFetcher.addPart('lib.no:submenu', {processor: submenuProcessor});
dataFetcher.addPart('lib.no:textblock', {processor: textBlockProcessor});
dataFetcher.addPart('lib.no:titleblock', {processor: titleBlockProcessor});
dataFetcher.addPart('lib.no:test', {processor: testProcessor});
