version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    assignees:
      - 'virtueme'
    reviewers:
      - 'virtueme'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    assignees:
      - 'virtueme'
    reviewers:
      - 'virtueme'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    assignees:
      - 'virtueme'
    reviewers:
      - 'virtueme'
