name: Enonic CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install project dependences
        run: npm install

      - name: Lint code and css
        run: npm run lint

      - name: Build jar file
        run: npm run rebuild

      - name: Build, Test and Deploy app
        uses: docker://enonic/enonic-ci:7.6-node
        env:
          ENONIC_CLI_REMOTE_URL: ${{ secrets.ENONIC_CLI_REMOTE_URL }}
          ENONIC_CLI_REMOTE_USER: ${{ secrets.ENONIC_CLI_REMOTE_USER }}
          ENONIC_CLI_REMOTE_PASS: ${{ secrets.ENONIC_CLI_REMOTE_PASS }}
        with:
          args: bash -c "enonic app install --file ./build/libs/*.jar"
